import fs from 'fs';
import path from 'path';
import { registry, type RegistryItem } from '../packages/react/src/registry';

const REGISTRY_DIR = path.resolve(process.cwd(), 'registry');
const REGISTRY_DEFAULT_DIR = path.join(REGISTRY_DIR, 'default');
const REACT_COMPONENTS_DIR = path.resolve(process.cwd(), 'packages/react/src/components');
const REACT_HOOKS_DIR = path.resolve(process.cwd(), 'packages/react/src/hooks');
const WEB_GENERATED_DIR = path.resolve(process.cwd(), 'apps/web/src/generated');
const WEB_REGISTRY_PAYLOAD_PATH = path.join(WEB_GENERATED_DIR, 'registry-payloads.ts');

type RegistryFile = RegistryItem['files'][number];

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function getFileNameWithoutExtension(filePath: string) {
  return path.basename(filePath, path.extname(filePath));
}

function getComponentName(file: RegistryFile) {
  if (file.target?.startsWith('@components/arcforge/')) {
    const [componentName] = file.target.replace('@components/arcforge/', '').split('/');
    return componentName;
  }

  const parts = file.path.split(/[\\/]/);
  return parts[parts.length - 2];
}

function getSourcePath(file: RegistryFile) {
  if (file.type === 'registry:hook') {
    return path.join(REACT_HOOKS_DIR, `${getFileNameWithoutExtension(file.path)}.ts`);
  }

  const componentName = getComponentName(file);
  if (!componentName) {
    throw new Error(`Unable to infer component source for ${file.path}`);
  }

  return path.join(REACT_COMPONENTS_DIR, componentName, 'index.tsx');
}

function getRegistryTargetPath(file: RegistryFile) {
  return path.resolve(process.cwd(), file.path);
}

async function buildRegistry() {
  console.log('Building registry...');

  ensureDir(REGISTRY_DIR);
  ensureDir(REGISTRY_DEFAULT_DIR);
  ensureDir(WEB_GENERATED_DIR);

  const registryItems = Object.values(registry);
  const registryPayloads: Record<string, RegistryItem & { files: Array<RegistryFile & { content: string }> }> = {};

  for (const item of registryItems) {
    const componentDir = path.join(REGISTRY_DEFAULT_DIR, item.name);
    ensureDir(componentDir);

    const filesWithContent = item.files.map((file) => {
      const sourcePath = getSourcePath(file);
      if (!fs.existsSync(sourcePath)) {
        throw new Error(`Source not found: ${sourcePath}`);
      }

      const sourceContent = fs.readFileSync(sourcePath, 'utf8');
      const targetPath = getRegistryTargetPath(file);
      ensureDir(path.dirname(targetPath));
      fs.writeFileSync(targetPath, sourceContent, 'utf8');

      return {
        ...file,
        content: sourceContent,
      };
    });

    // Write registry-item.json
    const itemJsonPath = path.join(componentDir, 'registry-item.json');
    fs.writeFileSync(itemJsonPath, JSON.stringify(item, null, 2), 'utf8');

    registryPayloads[item.name] = {
      ...item,
      files: filesWithContent,
    };

    console.log(`Generated registry item: ${item.name}`);
  }

  // Write root registry.json
  const rootRegistryPath = path.join(REGISTRY_DIR, 'registry.json');
  const rootRegistryData = {
    name: "arcforge",
    homepage: "https://TODO:VERCEL_URL",
    items: registryItems,
  };
  fs.writeFileSync(rootRegistryPath, JSON.stringify(rootRegistryData, null, 2), 'utf8');
  fs.writeFileSync(
    WEB_REGISTRY_PAYLOAD_PATH,
    [
      '/* This file is generated by tooling/registry-build.ts. Do not edit manually. */',
      '',
      `export const registryPayloads = ${JSON.stringify(registryPayloads, null, 2)} as const;`,
      '',
      'export type RegistryPayloadSlug = keyof typeof registryPayloads;',
      '',
    ].join('\n'),
    'utf8',
  );

  console.log('Registry build complete.');
}

buildRegistry().catch((err) => {
  console.error('Error building registry:', err);
  process.exit(1);
});
